### ISSUE TITLE
Error message when stopping the script

### ISSUE THREAD

**Issue by rmcarlsson** [thorrak/brewpi-esp8266#9] opened 2017-06-18 09:39 UTC
When I press the "stop scrip" button in the web-gui I get an error message in the stderr log:

Traceback (most recent call last):
File "/home/brewpi/brewpi.py", line 690, in 
dontrunfile = open(dontRunFilePath, "w")
NameError: name 'dontRunFilePath' is not defined

**Comment by rmcarlsson** [comment] 2017-06-18 12:29
It looks like it is not possible to stop a brew. 

I have used the legacy branch in Brewpi before and this clone appears to be broken, at least if you would like to use fermentation profiles.

Let me know if need any more logs or data.

**Comment by thorrak** [comment] 2017-06-19 02:58
I'm guessing something must hav ebeen damaged when I was doing the Fermentrack conversion of brewpi-script. When I'm working on testing to determine the root cause of #8, I'll see about resolving this as well. Sorry about that!

**Comment by thorrak** [comment] 2019-12-07 15:25
Closing this out, as all focus is now on either [Fermentrack](http://www.fermentrack.com/) or [BrewPiRemix](https://www.brewpiremix.com/) support.

**Closed by thorrak** 2019-12-07 15:25 UTC
